/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ConversationEntry {
  'color' : string,
  'sender' : string,
  'language' : string,
  'message' : string,
  'timestamp' : string,
  'expectedReply' : string,
}
export interface Locale {
  'code' : string,
  'countries' : Array<string>,
  'languageName' : string,
  'localeSymbol' : string,
  'default' : boolean,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'preferredLanguage' : [] | [string],
  'name' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'analyzeSentiment' : ActorMethod<[string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'convertToSentenceCase' : ActorMethod<[string], string>,
  'detectLanguage' : ActorMethod<[string], string>,
  'fetchSupportedLocales' : ActorMethod<[], Array<Locale>>,
  'generateLanguage' : ActorMethod<[string], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversationHistory' : ActorMethod<[Principal], Array<ConversationEntry>>,
  'getCurrentLocale' : ActorMethod<[], Locale>,
  'getDetectedLanguage' : ActorMethod<[], string>,
  'getFilteredConversationHistory' : ActorMethod<
    [Principal, string],
    Array<ConversationEntry>
  >,
  'getStaticAssistantMessage' : ActorMethod<[], string>,
  'getStaticMessage' : ActorMethod<[], string>,
  'getStaticTypingIndicator' : ActorMethod<[], undefined>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'parseMessages' : ActorMethod<[Array<string>], Array<string>>,
  'queueMessage' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveConversationEntry' : ActorMethod<[Uint8Array], undefined>,
  'sendTestJsonMessage' : ActorMethod<[], string>,
  'sendTestMessage' : ActorMethod<[], string>,
  'shouldAskCalmingQuestions' : ActorMethod<
    [],
    [
      boolean,
      string,
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
    ]
  >,
  'shouldEndOnSootingNote' : ActorMethod<[], [boolean, string]>,
  'shouldOfferGroundingTips' : ActorMethod<
    [],
    [boolean, string, string, [] | [string], [] | [string]]
  >,
  'shouldReflectRepeatWork' : ActorMethod<[], [boolean, string, string]>,
  'shouldSendTypingIndicator' : ActorMethod<[], boolean>,
  'simulateTypedMessage' : ActorMethod<[string], undefined>,
  'startTyping' : ActorMethod<[], undefined>,
  'stopTyping' : ActorMethod<[], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'trimText' : ActorMethod<[string], string>,
  'updateLocalMessage' : ActorMethod<[Uint8Array], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];