/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Locale = IDL.Record({
  'code' : IDL.Text,
  'countries' : IDL.Vec(IDL.Text),
  'languageName' : IDL.Text,
  'localeSymbol' : IDL.Text,
  'default' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'preferredLanguage' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
});
export const ConversationEntry = IDL.Record({
  'color' : IDL.Text,
  'sender' : IDL.Text,
  'language' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Text,
  'expectedReply' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'analyzeSentiment' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'convertToSentenceCase' : IDL.Func([IDL.Text], [IDL.Text], []),
  'detectLanguage' : IDL.Func([IDL.Text], [IDL.Text], []),
  'fetchSupportedLocales' : IDL.Func([], [IDL.Vec(Locale)], []),
  'generateLanguage' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversationHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ConversationEntry)],
      [],
    ),
  'getCurrentLocale' : IDL.Func([], [Locale], ['query']),
  'getDetectedLanguage' : IDL.Func([], [IDL.Text], ['query']),
  'getFilteredConversationHistory' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Vec(ConversationEntry)],
      ['query'],
    ),
  'getStaticAssistantMessage' : IDL.Func([], [IDL.Text], ['query']),
  'getStaticMessage' : IDL.Func([], [IDL.Text], []),
  'getStaticTypingIndicator' : IDL.Func([], [], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'parseMessages' : IDL.Func([IDL.Vec(IDL.Text)], [IDL.Vec(IDL.Text)], []),
  'queueMessage' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveConversationEntry' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
  'sendTestJsonMessage' : IDL.Func([], [IDL.Text], []),
  'sendTestMessage' : IDL.Func([], [IDL.Text], []),
  'shouldAskCalmingQuestions' : IDL.Func(
      [],
      [
        IDL.Bool,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [],
    ),
  'shouldEndOnSootingNote' : IDL.Func([], [IDL.Bool, IDL.Text], []),
  'shouldOfferGroundingTips' : IDL.Func(
      [],
      [IDL.Bool, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
    ),
  'shouldReflectRepeatWork' : IDL.Func([], [IDL.Bool, IDL.Text, IDL.Text], []),
  'shouldSendTypingIndicator' : IDL.Func([], [IDL.Bool], ['query']),
  'simulateTypedMessage' : IDL.Func([IDL.Text], [], []),
  'startTyping' : IDL.Func([], [], []),
  'stopTyping' : IDL.Func([], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'trimText' : IDL.Func([IDL.Text], [IDL.Text], []),
  'updateLocalMessage' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Locale = IDL.Record({
    'code' : IDL.Text,
    'countries' : IDL.Vec(IDL.Text),
    'languageName' : IDL.Text,
    'localeSymbol' : IDL.Text,
    'default' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'preferredLanguage' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
  });
  const ConversationEntry = IDL.Record({
    'color' : IDL.Text,
    'sender' : IDL.Text,
    'language' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Text,
    'expectedReply' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'analyzeSentiment' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'convertToSentenceCase' : IDL.Func([IDL.Text], [IDL.Text], []),
    'detectLanguage' : IDL.Func([IDL.Text], [IDL.Text], []),
    'fetchSupportedLocales' : IDL.Func([], [IDL.Vec(Locale)], []),
    'generateLanguage' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversationHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ConversationEntry)],
        [],
      ),
    'getCurrentLocale' : IDL.Func([], [Locale], ['query']),
    'getDetectedLanguage' : IDL.Func([], [IDL.Text], ['query']),
    'getFilteredConversationHistory' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Vec(ConversationEntry)],
        ['query'],
      ),
    'getStaticAssistantMessage' : IDL.Func([], [IDL.Text], ['query']),
    'getStaticMessage' : IDL.Func([], [IDL.Text], []),
    'getStaticTypingIndicator' : IDL.Func([], [], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'parseMessages' : IDL.Func([IDL.Vec(IDL.Text)], [IDL.Vec(IDL.Text)], []),
    'queueMessage' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveConversationEntry' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
    'sendTestJsonMessage' : IDL.Func([], [IDL.Text], []),
    'sendTestMessage' : IDL.Func([], [IDL.Text], []),
    'shouldAskCalmingQuestions' : IDL.Func(
        [],
        [
          IDL.Bool,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [],
      ),
    'shouldEndOnSootingNote' : IDL.Func([], [IDL.Bool, IDL.Text], []),
    'shouldOfferGroundingTips' : IDL.Func(
        [],
        [IDL.Bool, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
      ),
    'shouldReflectRepeatWork' : IDL.Func(
        [],
        [IDL.Bool, IDL.Text, IDL.Text],
        [],
      ),
    'shouldSendTypingIndicator' : IDL.Func([], [IDL.Bool], ['query']),
    'simulateTypedMessage' : IDL.Func([IDL.Text], [], []),
    'startTyping' : IDL.Func([], [], []),
    'stopTyping' : IDL.Func([], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'trimText' : IDL.Func([IDL.Text], [IDL.Text], []),
    'updateLocalMessage' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };