/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface Locale {
    code: string;
    countries: Array<string>;
    languageName: string;
    localeSymbol: string;
    default: boolean;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface ConversationEntry {
    color: string;
    sender: string;
    language: string;
    message: string;
    timestamp: string;
    expectedReply: string;
}
export interface UserProfile {
    preferredLanguage?: string;
    name: string;
}
export interface http_header {
    value: string;
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    analyzeSentiment(text: string): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    convertToSentenceCase(text: string): Promise<string>;
    detectLanguage(text: string): Promise<string>;
    fetchSupportedLocales(): Promise<Array<Locale>>;
    generateLanguage(language: string): Promise<string>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getConversationHistory(user: Principal): Promise<Array<ConversationEntry>>;
    getCurrentLocale(): Promise<Locale>;
    getDetectedLanguage(): Promise<string>;
    getFilteredConversationHistory(user: Principal, localeFilter: string): Promise<Array<ConversationEntry>>;
    getStaticAssistantMessage(): Promise<string>;
    getStaticMessage(): Promise<string>;
    getStaticTypingIndicator(): Promise<void>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isAdmin(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    parseMessages(messages: Array<string>): Promise<Array<string>>;
    queueMessage(message: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveConversationEntry(encodedEntry: Uint8Array): Promise<void>;
    sendTestJsonMessage(): Promise<string>;
    sendTestMessage(): Promise<string>;
    shouldAskCalmingQuestions(): Promise<[boolean, string, string, string, string | null, string | null, string | null]>;
    shouldEndOnSootingNote(): Promise<[boolean, string]>;
    shouldOfferGroundingTips(): Promise<[boolean, string, string, string | null, string | null]>;
    shouldReflectRepeatWork(): Promise<[boolean, string, string]>;
    shouldSendTypingIndicator(): Promise<boolean>;
    simulateTypedMessage(message: string): Promise<void>;
    startTyping(): Promise<void>;
    stopTyping(): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    trimText(input: string): Promise<string>;
    updateLocalMessage(entry: Uint8Array): Promise<void>;
}
import type { UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async analyzeSentiment(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeSentiment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeSentiment(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async convertToSentenceCase(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.convertToSentenceCase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.convertToSentenceCase(arg0);
            return result;
        }
    }
    async detectLanguage(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.detectLanguage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.detectLanguage(arg0);
            return result;
        }
    }
    async fetchSupportedLocales(): Promise<Array<Locale>> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchSupportedLocales();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchSupportedLocales();
            return result;
        }
    }
    async generateLanguage(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateLanguage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateLanguage(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getConversationHistory(arg0: Principal): Promise<Array<ConversationEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversationHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversationHistory(arg0);
            return result;
        }
    }
    async getCurrentLocale(): Promise<Locale> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentLocale();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentLocale();
            return result;
        }
    }
    async getDetectedLanguage(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getDetectedLanguage();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDetectedLanguage();
            return result;
        }
    }
    async getFilteredConversationHistory(arg0: Principal, arg1: string): Promise<Array<ConversationEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilteredConversationHistory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilteredConversationHistory(arg0, arg1);
            return result;
        }
    }
    async getStaticAssistantMessage(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaticAssistantMessage();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaticAssistantMessage();
            return result;
        }
    }
    async getStaticMessage(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaticMessage();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaticMessage();
            return result;
        }
    }
    async getStaticTypingIndicator(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.getStaticTypingIndicator();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStaticTypingIndicator();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async parseMessages(arg0: Array<string>): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.parseMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.parseMessages(arg0);
            return result;
        }
    }
    async queueMessage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.queueMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.queueMessage(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n9(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n9(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveConversationEntry(arg0: Uint8Array): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveConversationEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveConversationEntry(arg0);
            return result;
        }
    }
    async sendTestJsonMessage(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendTestJsonMessage();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendTestJsonMessage();
            return result;
        }
    }
    async sendTestMessage(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendTestMessage();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendTestMessage();
            return result;
        }
    }
    async shouldAskCalmingQuestions(): Promise<[boolean, string, string, string, string | null, string | null, string | null]> {
        if (this.processError) {
            try {
                const result = await this.actor.shouldAskCalmingQuestions();
                return [
                    result[0],
                    result[1],
                    result[2],
                    result[3],
                    from_candid_opt_n6(this._uploadFile, this._downloadFile, result[4]),
                    from_candid_opt_n6(this._uploadFile, this._downloadFile, result[5]),
                    from_candid_opt_n6(this._uploadFile, this._downloadFile, result[6])
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.shouldAskCalmingQuestions();
            return [
                result[0],
                result[1],
                result[2],
                result[3],
                from_candid_opt_n6(this._uploadFile, this._downloadFile, result[4]),
                from_candid_opt_n6(this._uploadFile, this._downloadFile, result[5]),
                from_candid_opt_n6(this._uploadFile, this._downloadFile, result[6])
            ];
        }
    }
    async shouldEndOnSootingNote(): Promise<[boolean, string]> {
        if (this.processError) {
            try {
                const result = await this.actor.shouldEndOnSootingNote();
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.shouldEndOnSootingNote();
            return [
                result[0],
                result[1]
            ];
        }
    }
    async shouldOfferGroundingTips(): Promise<[boolean, string, string, string | null, string | null]> {
        if (this.processError) {
            try {
                const result = await this.actor.shouldOfferGroundingTips();
                return [
                    result[0],
                    result[1],
                    result[2],
                    from_candid_opt_n6(this._uploadFile, this._downloadFile, result[3]),
                    from_candid_opt_n6(this._uploadFile, this._downloadFile, result[4])
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.shouldOfferGroundingTips();
            return [
                result[0],
                result[1],
                result[2],
                from_candid_opt_n6(this._uploadFile, this._downloadFile, result[3]),
                from_candid_opt_n6(this._uploadFile, this._downloadFile, result[4])
            ];
        }
    }
    async shouldReflectRepeatWork(): Promise<[boolean, string, string]> {
        if (this.processError) {
            try {
                const result = await this.actor.shouldReflectRepeatWork();
                return [
                    result[0],
                    result[1],
                    result[2]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.shouldReflectRepeatWork();
            return [
                result[0],
                result[1],
                result[2]
            ];
        }
    }
    async shouldSendTypingIndicator(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.shouldSendTypingIndicator();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.shouldSendTypingIndicator();
            return result;
        }
    }
    async simulateTypedMessage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.simulateTypedMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.simulateTypedMessage(arg0);
            return result;
        }
    }
    async startTyping(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startTyping();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startTyping();
            return result;
        }
    }
    async stopTyping(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.stopTyping();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.stopTyping();
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async trimText(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.trimText(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trimText(arg0);
            return result;
        }
    }
    async updateLocalMessage(arg0: Uint8Array): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLocalMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLocalMessage(arg0);
            return result;
        }
    }
}
function from_candid_UserProfile_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    preferredLanguage: [] | [string];
    name: string;
}): {
    preferredLanguage?: string;
    name: string;
} {
    return {
        preferredLanguage: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.preferredLanguage)),
        name: value.name
    };
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserProfile_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    preferredLanguage?: string;
    name: string;
}): {
    preferredLanguage: [] | [string];
    name: string;
} {
    return {
        preferredLanguage: value.preferredLanguage ? candid_some(value.preferredLanguage) : candid_none(),
        name: value.name
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
